version: "2"
linters:
  enable:
    - gocritic
    - govet
    - ineffassign
    - misspell
    - staticcheck
    - unconvert
  disable:
    - gocyclo
    - goconst
    - gocognit
    - gochecknoglobals
    - gochecknoinits