CREATE TABLE IF NOT EXISTS Users (
    ID SERIAL PRIMARY KEY,
    Name VARCHAR(30) NOT NULL,
);

CREATE TABLE IF NOT EXISTS Wallets (
    ID SERIAL PRIMARY KEY,
    Name VARCHAR(30) NOT NULL,
    Currency VARCHAR(3) CHECK(Currency IN('EUR', 'USD', 'RUB'))
    OwnerID REFERENCES Users(ID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS Categories (
    ID SERIAL PRIMARY KEY,
    Name VARCHAR(30) NOT NULL,
    WalletID REFERENCES Wallets(ID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS Transactions (
    ID SERIAL PRIMARY KEY,
    WalletID REFERENCES Wallets(ID) ON DELETE CASCADE,
    Sum INTEGER NOT NULL,
    CategoryID REFERENCES Categories(ID) ON DELETE CASCADE /*Добавить проверку*/
)