CREATE TABLE IF NOT EXISTS Users (
    ID SERIAL PRIMARY KEY,
    Name VARCHAR(50) NOT NULL,
    Email VARCHAR(50) UNIQUE NOT NULL,
    Password VARCHAR(200) NOT NULL
);

CREATE TABLE IF NOT EXISTS Wallets (
    ID SERIAL PRIMARY KEY,
    Name VARCHAR(30) NOT NULL,
    Currency VARCHAR(3) CHECK(Currency IN('EUR', 'USD', 'RUB')) NOT NULL,
    OwnerID INTEGER REFERENCES Users(ID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS Categories (
    ID SERIAL PRIMARY KEY,
    Name VARCHAR(30) NOT NULL,
    WalletID INTEGER REFERENCES Wallets(ID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS Transactions (
    ID SERIAL PRIMARY KEY,
    WalletID INTEGER REFERENCES Wallets(ID) ON DELETE CASCADE,
    Sum INTEGER NOT NULL,
    CategoryID INTEGER REFERENCES Categories(ID) ON DELETE CASCADE /*Добавить проверку*/
);