CREATE TABLE IF NOT EXISTS Users (
    ID SERIAL PRIMARY KEY,
    Name VARCHAR(50) NOT NULL,
    Nickname VARCHAR(50) UNIQUE NOT NULL,
    Password VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS Wallets (
    ID SERIAL PRIMARY KEY,
    Name VARCHAR(50) NOT NULL,
    Currency VARCHAR(3) NOT NULL,
    OwnerID INTEGER NOT NULL,
    FOREIGN KEY (OwnerID) REFERENCES Users(ID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS Categories (
    ID SERIAL PRIMARY KEY,
    Name VARCHAR(50) NOT NULL,
    OwnerID INTEGER NOT NULL,
    FOREIGN KEY (OwnerID) REFERENCES Users(ID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS Operations (
    ID SERIAL PRIMARY KEY,
    Name VARCHAR(50) NOT NULL,
    WalletID INTEGER NOT NULL,
    FOREIGN KEY (WalletID) REFERENCES Wallets(ID) ON DELETE CASCADE,
    Sum FLOAT NOT NULL,
    Date DATE NOT NULL,
    Place VARCHAR(50) NOT NULL,
    CategoryID INTEGER NOT NULL,
    FOREIGN KEY (CategoryID) REFERENCES Categories(ID) ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS Operations_Name_Index ON Operations USING HASH(Name);